### PR TITLE
Adding Russian

### PR DESCRIPTION
**Pull request by applocalizations**

### CODE REVIEW

**Comment by PEM--** [comment]
Thanks Eric. It needs some polish. I will do it for you and send your PR to Orion once mine is integrated. With your skillset, Orion should put a special message for guys who would like their site translated. That could bring you some customers :wink:

**Comment by applocalizations** [comment]
Hi Pierre, 
Customers might be beneficial. Towards the end of the week I would like to add a couple more languages that I know. I am happy to contribute. Let me know what else I might be able to help, especially with programming.

**Comment by PEM--** [comment]
Hi Eric, Very good to know. @nicolaslopezj has integrated our PR into Orion v1.1, the next release branch. Next time, it's going to be even easier. I don't know if you've seen it this morning on Gitter. We were having discussions about a Sass for developing Meteor and Orion apps. I'm sure that your knowledge would be an incredible asset on that.

**Comment by applocalizations** [comment]
Hi Pierre, Thanks for the update. I haven't had a chance to check out
Gitter yet. I am teaching an Objective-C class tonight. I would like to
participate. What do you recommend? I'll be in Gitter tomorrow evening. Do
you have a personal email account? Eric

**Comment by PEM--** [comment]
Let's chat tomorrow on Gitter. We will be able to set a private room. Better that putting my email on Github :wink:

**Comment by applocalizations** [comment]
I agree. Let's chat tomorrow night.

**Pull request merged**
